### ISSUE TITLE
Known issues of BrainVISA 5.0.0 (and workarounds)

### ISSUE THREAD

**Issue by ylep** [brainvisa/brainvisa.github.io#36]
**BrainVISA 5.0.1 has been released now**. If you experience issues with BrainVISA 5.0.0, please try the latest version.
Issues with BrainVISA 5.0.1 should be reported [over there](https://github.com/brainvisa/brainvisa.github.io/issues/37).

Check boxes mean that the fix has been pushed into the `5.0.1` release.

- [x] https://github.com/brainvisa/casa-distro/issues/253: `jupyter notebook` fails because of a missing dependency: `jsonschema`.
  **Workaround:**
  ```shell
  bv bash
  pip install --user jsonschema
  ```
- [ ] https://github.com/brainvisa/anatomist-free/issues/25: textured wireframe meshes appear black in Anatomist
  **Workaround:** see https://github.com/brainvisa/anatomist-free/issues/25
- [X] https://github.com/brainvisa/casa-distro/issues/254: in NeuroSpin the user-specific home is in an incorrect directory
- [x] Issue with the HipHop private toolbox (fixed by Denis)

Issues specific to the Virtual Machine distribution format:
- [x] Cannot mount directories shared from the host in the container: user `brainvisa` does not have permission.
  **Workaround:**: `sudo addgroup brainvisa vboxfs` (password: `brainvisa`)
- [x] https://github.com/brainvisa/casa-distro/issues/252: the VM has a French keyboard layout (azerty), and changing it is not obvious.
  **Workaround:**: see https://github.com/brainvisa/casa-distro/issues/252

Issues with libraries and applications:
- [x] incomplete python bindings to non-linear transformations FfdTransformation subclasses and their IO. No ticket has been opened but they have been fixed. No possible workaround in 5.0.0.
- [x] a few minor fixes in Anatomist

**Comment by sapetnioc** [comment]
I am busy with important changes on CatiDB and a need to have a transition as short as possible. I will get back to BrainVISA next week.

**Comment by denisri** [comment]
The new infrastructure should allow to make more frequent releases/bug fixes. Let's do it ;)
(I have uploaded new run/dev singularity images for the notebook problem)
