### ISSUE TITLE
Known issues of BrainVISA 5.0.1

### ISSUE THREAD

**Issue by ylep** [brainvisa/brainvisa.github.io#37]
@brainvisa/release This issue is to keep track of known problems with the BrainVISA 5.0.1 release. It may help us decide if we want to make a 5.0.2 release at some point.

**Please edit this description to add issues that you are aware of**. Check boxes mean that the fix has been pushed to the `5.0` branch.

- [x] https://github.com/brainvisa/soma-io/issues/9: unable to read Nifti files whose name is shorter than 7 characters
- [X] https://github.com/brainvisa/casa-distro/issues/258: **all commands fail to start** if `nvidia-container-cli` returns an error. Workaround: uninstall `nvidia-container-cli` (`sudo apt-get remove nvidia-container-tools`). This will disable hardware OpenGL rendering.
- [X] Spurious `'`s in BrainVISA process documentations (fixed in https://github.com/brainvisa/axon/commit/9327c496c301aa59325e082b6094e3cb48b60953)
- [x] https://github.com/brainvisa/aims-free/issues/53: aimsalgo.resampleBucket() has a bug
- [x] https://github.com/brainvisa/axon/issues/46: Uncatched exceptions that occurs in BrainVISA lead to a crash of the application (it has been partially fixed, but many slots remain undecorated with @catch_gui_exception)
- [x] https://github.com/brainvisa/aims-free/issues/58: C++ headers dependency issue
- [x] https://github.com/brainvisa/axon/issues/47: Opening Graph file by clicking the "eye" button crashes BrainVISA
- [x] `cartoFSLmatToTrm.py` returns all-NaN transformation matrices, fixed in https://github.com/brainvisa/aims-free/commit/43429e91cd7f79760d45895c66c093af82c17b67.

**Comment by ylep** [comment]
BrainVISA 5.0.2 has been released now, please report any issues with it on https://github.com/brainvisa/brainvisa.github.io/issues/54.
