### ISSUE TITLE
Known issues for BrainVISA 5.0.3

### ISSUE THREAD

**Issue by nsouedet** [brainvisa/brainvisa.github.io#83]
This issue is to keep track of known problems with the BrainVISA **5.0.3** release. It may help us decide if/when we want to make a **5.0.4** release.

**Please edit this description to add issues that you are aware of**. Check boxes mean that the fix has been pushed to the release branch.

- [x] https://github.com/brainvisa/axon/issues/56
- [x] https://github.com/brainvisa/casa-distro/issues/284
- [x] brainvisa/aims-free#71
- [x] brainvisa/morphologist-gpl#1
- [x] brainvisa/axon#55
- [x] brainvisa/cortical_surface-gpl#1
- [x] brainvisa/anatomist-gpl#21
- [x] brainvisa/aims-free#73
- [x] brainvisa/casa-distro#296
- [x] DISCO fails under MATLAB R2021a (MATLAB syntax error)

**Comment by ylep** [comment]
Now that BrainVISA 5.0.4 is released, known issues are tracked here: https://github.com/brainvisa/brainvisa.github.io/issues/92
